### ISSUE TITLE
Any interest in publishing on CRAN?

### ISSUE THREAD

**Issue by zachzIAM** [philaris/figir#1]
Yassou Panagioti,

Thanks for writing `figir`, I use it in anger in a bunch of my workflows. I was wondering if you'd be interested in publishing it on CRAN? It would likely boost adoption, and (from a selfish perspective) make dependency resolution in an enterprise setting much easier.

**Comment by philaris** [comment]
Hi @zachzIAM, I am glad that you use the package. I did a small update and submitted to CRAN. Let's see if it will be accepted.

**Comment by philaris** [comment]
https://CRAN.R-project.org/package=figir @zachzIAM

**Comment by zachzIAM** [comment]
@philaris Nice one! Thank you very much
